name: Hello World from python

on: [push]

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
      -  name: Checkout code 
         uses: RemcoHalman/python-helloworld-action@b01903e6d4fd4d6f55d9652ad9fa7cc8f4bdf12b

      -  name: Hello World from Python
         uses: RemcoHalman/python-helloworld-action@v0.0.1
          
