name: Hello World from python

on: [push]

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
        - uses: actions/checkout@v2
        -name: Hello World from Python
           uses:
RemcoHalman/python-helloworld-action@v.0.0.1
          
